# This file contains values from Cookiecutter

default_context:
  project_name: "lotr-movie-sdk"
  project_description: "Lord Of TheRings Movie SDK - Test for LibLab"
  organization: "sciffer"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "sciffer"
  email: "shaly.c@gmail.com"
  version: "0.1.0"
  line_length: "120"
  create_example_template: "none"
